const PERSISTENT_MEMORY_PATTERNS = [
  // Spanish
  /\bmi nombre es\b/i,
  /\bme llamo\b/i,
  /\bsoy el fundador\b/i,
  /\bsoy la fundadora\b/i,
  /\bsoy fundador\b/i,
  /\bsoy fundadora\b/i,
  /\bnuestra empresa\b/i,
  /\bmi empresa\b/i,
  /\bmi startup\b/i,
  /\bnuestra startup\b/i,
  /\bnuestro producto\b/i,
  /\bnuestro servicio\b/i,
  /\bmi producto\b/i,
  /\bmi servicio\b/i,
  /\btrabajamos en\b/i,
  /\bnos dedicamos a\b/i,
  /\bla empresa se llama\b/i,
  /\bel producto se llama\b/i,
  /\bse llama\b/i,
  /\bhemos decidido\b/i,
  /\bdecidimos\b/i,
  /\bnuestro objetivo es\b/i,
  /\bmi objetivo es\b/i,
  /\bqueremos construir\b/i,
  /\bqueremos crear\b/i,
  /\bqueremos lanzar\b/i,
  /\bhemos lanzado\b/i,
  /\blanzamos\b/i,
  /\bnuestro mercado\b/i,
  /\bnuestros clientes\b/i,
  /\bnuestro cliente ideal\b/i,
  /\bnuestro modelo de negocio\b/i,
  /\bnuestro pricing\b/i,
  /\bnuestros precios\b/i,
  /\bnuestro equipo\b/i,
  /\bsoy ceo\b/i,
  /\bsoy ceo de\b/i,
  /\bsoy director\b/i,
  /\bsoy directora\b/i,

  // English
  /\bmy name is\b/i,
  /\bmy company is\b/i,
  /\bmy startup is\b/i,
  /\bour company\b/i,
  /\bour startup\b/i,
  /\bmy product\b/i,
  /\bour product\b/i,
  /\bmy service\b/i,
  /\bour service\b/i,
  /\bi am building\b/i,
  /\bi'm building\b/i,
  /\bwe are building\b/i,
  /\bwe're building\b/i,
  /\bwe work on\b/i,
  /\bwe work in\b/i,
  /\bwe are working on\b/i,
  /\bwe're working on\b/i,
  /\bthe company is called\b/i,
  /\bthe product is called\b/i,
  /\bit is called\b/i,
  /\bit's called\b/i,
  /\bwe decided\b/i,
  /\bwe have decided\b/i,
  /\bour goal is\b/i,
  /\bmy goal is\b/i,
  /\bwe want to build\b/i,
  /\bwe want to create\b/i,
  /\bwe want to launch\b/i,
  /\bwe launched\b/i,
  /\bwe have launched\b/i,
  /\bour market\b/i,
  /\bour customers\b/i,
  /\bmy customers\b/i,
  /\bour ideal customer\b/i,
  /\bour business model\b/i,
  /\bmy business model\b/i,
  /\bour pricing\b/i,
  /\bmy pricing\b/i,
  /\bour prices\b/i,
  /\bmy prices\b/i,
  /\bour team\b/i,
  /\bmy team\b/i,
  /\bi am the founder\b/i,
  /\bi'm the founder\b/i,
  /\bi am founder\b/i,
  /\bi'm founder\b/i,
  /\bi am ceo\b/i,
  /\bi'm ceo\b/i,
  /\bi am the ceo\b/i,
  /\bi'm the ceo\b/i,
  /\bi am director\b/i,
  /\bi'm director\b/i,
];

export function shouldExtractMemory(message: string): boolean {
  const normalized = message.trim();

  if (!normalized) {
    return false;
  }

  return PERSISTENT_MEMORY_PATTERNS.some((pattern) =>
    pattern.test(normalized),
  );
}
